# Generated by Django 2.0.2 on 2018-07-18 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=15)),
                ('book_name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=100)),
                ('translator', models.CharField(max_length=40, null=True)),
                ('press', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('borrowed_times', models.IntegerField(default=0)),
                ('state_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='borrow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('end_time', models.DateTimeField()),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.book_list')),
            ],
        ),
        migrations.CreateModel(
            name='login_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cretime', models.DateTimeField()),
                ('confirm_code', models.SmallIntegerField(default=0)),
                ('expiry_time', models.DateTimeField()),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.book_list')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_id', models.CharField(max_length=12)),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=14)),
                ('holds', models.IntegerField(default=0, null=True)),
                ('cretime', models.DateTimeField()),
                ('last_time', models.DateTimeField(null=True)),
                ('cancellation', models.BooleanField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.user'),
        ),
        migrations.AddField(
            model_name='login_record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.user'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='previous',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.user'),
        ),
        migrations.AddField(
            model_name='book_list',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.user'),
        ),
    ]
