# Generated by Django 2.0.2 on 2018-07-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibrarySys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='owner',
            new_name='requster',
        ),
        migrations.AddField(
            model_name='book_list',
            name='book_image',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='book_list',
            name='profiles',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
