# Generated by Django 2.0.2 on 2018-07-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibrarySys', '0002_auto_20180718_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_list',
            name='price',
            field=models.FloatField(),
        ),
    ]
