# Generated by Django 2.0.2 on 2018-07-21 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibrarySys', '0003_auto_20180718_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_short_comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField(max_length=300)),
                ('comment_time', models.DateTimeField()),
                ('like_num', models.IntegerField(default=0)),
                ('unlike_num', models.IntegerField(default=0)),
                ('collect_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Book_short_comment_like_and_collection_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('like_state', models.BooleanField(default=0)),
                ('unlike_state', models.BooleanField(default=0)),
                ('collection_state', models.BooleanField(default=0)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.Book_short_comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.User')),
            ],
        ),
        migrations.AlterField(
            model_name='book_list',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.User'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.Book_list'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='previous',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.User'),
        ),
        migrations.AlterField(
            model_name='login_record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.User'),
        ),
        migrations.AlterField(
            model_name='request',
            name='book_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.Book_list'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.User'),
        ),
        migrations.AddField(
            model_name='book_short_comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.Book_list'),
        ),
        migrations.AddField(
            model_name='book_short_comment',
            name='commentator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.User'),
        ),
    ]
