# Generated by Django 2.0.2 on 2018-07-24 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibrarySys', '0005_auto_20180723_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('violation_type', models.SmallIntegerField()),
                ('cretime', models.DateTimeField()),
                ('treat_state', models.BooleanField(default=1)),
                ('treat_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='active_violations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='violation_times',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book_list',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.User'),
        ),
        migrations.AlterField(
            model_name='book_short_comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.Book_list'),
        ),
        migrations.AlterField(
            model_name='book_short_comment',
            name='commentator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.User'),
        ),
        migrations.AlterField(
            model_name='book_short_comment_like_and_collection_record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.User'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.Book_list'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='previous',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.User'),
        ),
        migrations.AlterField(
            model_name='login_record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.User'),
        ),
        migrations.AlterField(
            model_name='request',
            name='book_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.Book_list'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.User'),
        ),
        migrations.AddField(
            model_name='violation_record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LibrarySys.User'),
        ),
    ]
